server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intern_network
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: job_schema
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: false
    #schemas: job_schema
    #baseline-on-migrate: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: TRACE
    org.springframework.web.servlet.mvc.method.annotation: TRACE

services:
  profile:
    base-url: http://localhost:8082

  skill:
    base-url: http://localhost:8086

URL_AI_NLP: http://localhost:8087