server:
  port: ${AI_NLP_PORT:8087}

spring:
  application:
    name: ai-nlp-service

logging:
  level:
    root: INFO
    com.backend.ai_nlp_service: DEBUG

mapbox:
  geocoding-base-url: https://api.mapbox.com/geocoding/v5/mapbox.places
  token: ${MAPBOX_TOKEN}
