server:
  port: 8080

app:
  jwt:
    secret: "a8e33b4cd23905e1cfdac93858f74db34770b55e2bcb95a7d70563fd54c16b0b"

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, InternshipGateway
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/profile/**

        - id: job-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/job/**

        - id: message-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/message/**
          filters:
            - StripPrefix=1

        - id: cv-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/cv/**
          filters:
            - StripPrefix=1
