server:
  port: ${MESSAGE_PORT:8084}

spring:
  application:
    name: message-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:intern_network}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${MESSAGE_SCHEMA:message_schema}
        jdbc.time_zone: UTC

  # Flyway
  flyway:
    enabled: false

  # Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false

  # Multipart (file upload)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

service:
  profile:
    base-url: http://localhost:8082/api/profile/internal