server:
  port: 8085

spring:
  application:
    name: cv-service

  # ===============================
  # PostgreSQL DataSource
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/intern_network
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # ===============================
  # JPA / Hibernate
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # ===============================
  # Multipart (Upload file)
  # ===============================
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB

# ===============================
# JWT Secret (TODO: move to .env later)
# ===============================
jwt:
  secret: a8e33b4cd23905e1cfdac93858f74db34770b55e2bcb95a7d70563fd54c16b0b

# ===============================
# AWS S3 Configuration
# ===============================
aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}