server:
  port: ${CV_PORT:8085}

spring:
  application:
    name: cv-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:intern_network}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${CV_SCHEMA:cv_schema}
        jdbc.time_zone: UTC

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB


jwt:
  secret: ${JWT_SECRET}


aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

URL_AI_NLP: http://localhost:8087

services:
  profile:
    base-url: http://localhost:8082